server: eng-selenium-test.groundwork.groundworkopensource.com
grid: none
browser: 
headless: false
clear_cookies: false
agent: none
name: enterprise
version: 7.0.0
bitrock_built: br288
gw_build: gw1589
